# Generated by Django 4.0.6 on 2022-09-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basyal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='namet',
            field=models.CharField(default='study', max_length=100),
            preserve_default=False,
        ),
    ]
